###############################
## SERVICIO MARIADB RESTAPI  ##
###############################
apiVersion: v1
kind: Service
metadata:
  name: srv-mariadb
  labels:
    app: restapi
spec:
  type: LoadBalancer
  ports:
    - port: 3306
  selector:
    app: restapi
    tier: mariadb
  #clusterIP: None
---
#############################
## DEPLOY MARIADB RESTAPI  ##
#############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: restapi
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: restapi
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: restapi
        tier: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5
          ports:
            - containerPort: 3306
              name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: prueba
            - name: MYSQL_DATABASE
              value: apirest
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-mariadb